name: bluebuild
on:
  schedule:
    - cron: "00 17 * * *" # build at 17:00 UTC every day 
                          # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  pull_request:
  workflow_dispatch: # allow manually triggering builds
jobs:
  event:
    name: Event
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Event
        run: |
          cat "$GITHUB_EVENT_PATH"
          sudo podman info
          sudo /bin/bash -c 'echo "$PATH"'
          sudo -E /bin/bash -c 'echo "$PATH"'
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here 
          - recipe.yml
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
       # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@96-quotation-of-number-is-not-interpreted-correctly-by-bluebuild-cli
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          pr_event_number: ${{ github.event.number }}
          build_opts: "-v -B buildah"
          rechunk: true
